/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

//#ifndef MYSELECTIONS
//#define MYSELECTIONS


#include "TCut.h"
#include "TLorentzVector.h"
using namespace std;

class MySelections {
	public:
		MySelections() {} ; 
		MySelections(const char *name, const char *title){ SetValue(); };
		MySelections(const MySelections& other, const char* name=0) ;
		inline virtual ~MySelections() { };
	
		void SetValue(){
		
			m_Ecms = 3.097;

			//cut
			c_mpi0 = "mgg > 0.11 && mgg < 0.15";
		
		
		};


		double GetEcms(){return m_Ecms;};

		TLorentzVector GetP4cms(){
			TLorentzVector cms_p4(0.011*m_Ecms ,0,0, m_Ecms);
			return cms_p4;
		};

		TCut GetPi0Cut(){return c_mpi0;};

		double GetMassPi0(){return 134.977*0.001;};
		double GetMassLambda(){return 1115.683*0.001;};
		double GetMassXim(){return 1321.71*0.001;};
		double GetMassSigmam(){return 1197.449*0.001;};
		double GetMassSigmap(){return 1189.37*0.001;};



	private:
		double m_Ecms;
		TCut c_mpi0;

};

//#endif

